# mysql
spring:
  datasource:
    # MySql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unimelbcoder?useUnicode=true&characterEncoding=utf8&SSL=false&serverTimezone=UTC
    username: root
    password: Tgy998899880
  data:
    redis:
      host: localhost
      port: 6379
      password: rds123456
      timeout: 3000
      # 连接超时
      connectTimeout: 5000

jwt:
  secret: qnAqsQa7600vrTBcr1WB8P8dg4cbgS5i8LZGjWnpREL
  expiration: 86400


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model

rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: admin
  password: admin
  virtualhost: /
  switch_flag: false # 默认为false，需要时改为true打开mq服务
  pool_size: 5

server:
  port: 9001